on:
  push:
    branches:
      - 'release/**'

env:
  CR_NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GIT_BRANCH: ${{ vars.GITHUB_REF_NAME }}

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
        with:
          node-version: '18'
      - run: 'npm ci'
      - run: 'npm run dev npmPublish'
      # - run: npm install -g bats
      # - run: bats -v
